import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeArchContextModel } from "../../model-store-yaml/src/index";
import { assertNoHumanEditableGeneratedSection, reconcileGeneratedProjection } from "../src/index";

describe("@archcontext/reconcile-engine", () => {
  test("rebuilds generated projection when no human section exists", () => {
    const root = mkdtempSync(join(tmpdir(), "archctx-reconcile-"));
    try {
      initializeArchContextModel(root, "Reconcile Test");
      expect(reconcileGeneratedProjection(root)).toEqual({ rebuilt: true, preservedHumanSections: true });
      expect(readFileSync(join(root, ".archcontext/generated/ARCHITECTURE.md"), "utf8")).toContain("Generated by ArchContext");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("refuses to overwrite human-editable generated sections", () => {
    const root = mkdtempSync(join(tmpdir(), "archctx-reconcile-"));
    try {
      initializeArchContextModel(root, "Reconcile Test");
      writeFileSync(join(root, ".archcontext/generated/ARCHITECTURE.md"), "<!-- BEGIN HUMAN -->\nmanual note\n", "utf8");
      expect(() => assertNoHumanEditableGeneratedSection(root)).toThrow("human-editable");
      expect(() => reconcileGeneratedProjection(root)).toThrow("human-editable");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
