import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { digestJson, stableYaml, type Json, type ModelStorePort, type ModelValidationResult, type WorkspaceRef } from "@archcontext/contracts";
import { validateAdrAppliesTo } from "@archcontext/core/architecture-domain";
import { assertPathHasNoSymlinkSegments, writeFileWithoutFollowingSymlinks } from "@archcontext/core/changeset-engine";

export interface ModelFile {
  path: string;
  schemaVersion: string;
  digest: string;
  body: string;
}

export const ARCHCONTEXT_DIR = ".archcontext";
const GENERATED_ARCHITECTURE_PATH = ".archcontext/generated/ARCHITECTURE.md";
const GENERATED_ARCHITECTURE_BODY = [
  "<!-- Generated by ArchContext. Do not edit by hand. -->",
  "",
  "# Architecture",
  "",
  "Model projection is generated from `.archcontext/model`.",
  ""
].join("\n");

export interface GeneratedProjectionOperation {
  path: string;
  expectedHash: string;
  body: string;
  operation: "render_projection" | "delete_entity";
}

export function createDefaultManifest(productId: string, productName: string): Json {
  return {
    schemaVersion: "archcontext.manifest/v1",
    codeFacts: { provider: "codegraph", mode: "embedded", required: true },
    content: {
      decisions: ".archcontext/decisions",
      generated: ".archcontext/generated",
      policies: ".archcontext/policies",
      practices: ".archcontext/practices",
      projections: ".archcontext/projections"
    },
    generated: { commitToGit: true, formats: ["markdown", "mermaid"] },
    model: { layout: "split", root: ".archcontext/model" },
    privacy: {
      cloudContentUpload: "deny",
      localTunnel: { includeSourceByDefault: false, maxResultBytes: 8192 }
    },
    product: { governanceLevel: "auto", id: productId, name: productName },
    review: {
      failOn: ["invalid-schema", "prohibited-dependency", "unjustified-compatibility", "stale-context", "incomplete-intervention"]
    },
    runtime: { checkpoint: { changedFileThreshold: 20, requiredBeforeComplete: true }, contextBudgetBytes: 12288 }
  };
}

export function createDefaultProjectionTargetManifest(): Json {
  return {
    schemaVersion: "archcontext.projection-target-manifest/v1",
    rendererVersion: "archcontext.docs-renderer/v1",
    ownership: {
      humanAuthoredRegions: "preserve",
      generatedRegions: "replace-by-marker",
      ambiguousOwnership: "reject"
    },
    placementRules: [
      {
        id: "projection_rule.architecture.index",
        targetType: "architecture-index",
        scope: { kind: "repository" },
        pathTemplate: "docs/architecture/index.md",
        ownership: "mixed",
        format: "markdown"
      },
      {
        id: "projection_rule.entity.summary",
        targetType: "entity-summary",
        scope: { kind: "entity", entityKind: "*" },
        pathTemplate: "docs/architecture/modules/{stableId}.md",
        ownership: "mixed",
        format: "markdown"
      },
      {
        id: "projection_rule.relation.summary",
        targetType: "relation-summary",
        scope: { kind: "relation" },
        pathTemplate: "docs/architecture/relations/{stableId}.md",
        ownership: "mixed",
        format: "markdown"
      },
      {
        id: "projection_rule.decision.index",
        targetType: "decision-index",
        scope: { kind: "decision" },
        pathTemplate: "docs/architecture/decisions/index.md",
        ownership: "mixed",
        format: "markdown"
      },
      {
        id: "projection_rule.architecture.changelog",
        targetType: "architecture-changelog",
        scope: { kind: "changelog" },
        pathTemplate: "docs/architecture/changelog.md",
        ownership: "mixed",
        format: "markdown"
      },
      {
        id: "projection_rule.diagram.mermaid",
        targetType: "diagram-mermaid",
        scope: { kind: "diagram", id: "architecture" },
        pathTemplate: "docs/architecture/diagrams/architecture.mmd",
        ownership: "generated",
        format: "mermaid"
      },
      {
        id: "projection_rule.diagram.structurizr",
        targetType: "diagram-structurizr",
        scope: { kind: "diagram", id: "architecture" },
        pathTemplate: "docs/architecture/diagrams/architecture.structurizr.json",
        ownership: "generated",
        format: "structurizr-json"
      },
      {
        id: "projection_rule.diagram.likec4",
        targetType: "diagram-likec4",
        scope: { kind: "diagram", id: "architecture" },
        pathTemplate: "docs/architecture/diagrams/architecture.likec4",
        ownership: "generated",
        format: "likec4"
      },
      {
        id: "projection_rule.agent-context.claude",
        targetType: "agent-context",
        scope: { kind: "entity", entityKind: "capability" },
        pathTemplate: "{primarySourceDir}/CLAUDE.md",
        ownership: "mixed",
        format: "markdown"
      },
      {
        id: "projection_rule.agent-context.agents",
        targetType: "agent-context",
        scope: { kind: "entity", entityKind: "capability" },
        pathTemplate: "{primarySourceDir}/AGENTS.md",
        ownership: "mixed",
        format: "markdown"
      }
    ]
  };
}

/** Raised instead of writing when `init` would replace or complete an existing model (#167). */
export class ArchContextInitRefusedError extends Error {
  constructor(readonly existingPaths: string[]) {
    super(`archcontext-init-refused: .archcontext is already initialized or partially initialized (${existingPaths.join(", ")}); init never overwrites an existing model — change it through a ChangeSet, or remove these files deliberately before re-initializing`);
    this.name = "ArchContextInitRefusedError";
  }
}

/**
 * Creates the initial model. The files it writes are authoritative, so it is create-only: if any
 * of them already exists — even as a dangling symlink — nothing is written; each file is created
 * atomically without following symlinks in any path segment; and a failure part-way removes the
 * files this call created, so a failed init never leaves a silently half-initialized model.
 */
export function initializeArchContextModel(root: string, productName = "ArchContext Project"): void {
  const productId = `product.${productName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "app"}`;
  const files: Array<{ path: string; body: string }> = [];
  const addYaml = (path: string, value: Json) => files.push({ path, body: stableYaml(value) });
  addYaml(".archcontext/manifest.yaml", createDefaultManifest(productId, productName));
  addYaml(".archcontext/product.yaml", {
    schemaVersion: "archcontext.product/v1",
    id: productId,
    name: productName,
    purpose: "Capture product intent for architecture-aware agent work.",
    users: [{ id: "developer", description: "Developer using an agentic coding runtime." }],
    capabilities: ["architecture-context"],
    successCriteria: ["Agent tasks bind to architecture context before completion."],
    nonGoals: [],
    riskDomains: []
  });
  addYaml(".archcontext/model/nodes/capability.architecture-context.yaml", {
    schemaVersion: "archcontext.node/v2",
    id: "capability.architecture-context",
    kind: "capability",
    name: "Architecture Context",
    status: "active",
    summary: "Keeps product and architecture intent available to coding agents."
  });
  addYaml(".archcontext/policies/review.yaml", {
    schemaVersion: "archcontext.policy/v1",
    id: "policy.review",
    failOn: ["invalid-schema", "stale-context", "unjustified-compatibility"]
  });
  files.push({ path: ".archcontext/projections/targets.json", body: `${JSON.stringify(createDefaultProjectionTargetManifest(), null, 2)}\n` });

  // The repository root is the trusted containment boundary (it may itself be reached through a
  // symlink); only paths below it are checked. Creating it keeps init usable on a fresh directory.
  mkdirSync(root, { recursive: true });
  const existing = files.filter((file) => {
    assertPathHasNoSymlinkSegments(root, file.path);
    return lstatIfExists(resolve(root, file.path)) !== undefined;
  }).map((file) => file.path);
  if (existing.length > 0) throw new ArchContextInitRefusedError(existing);

  const created: string[] = [];
  try {
    for (const file of files) {
      writeFileWithoutFollowingSymlinks({ root, path: file.path, body: withTrailingNewline(file.body), expectedHash: "missing" });
      created.push(file.path);
    }
    // Part of the same all-or-nothing step: a failed rebuild must not leave an initialized model
    // behind that would refuse every retry.
    rebuildGeneratedProjection(root);
  } catch (error) {
    for (const path of created.reverse()) rmSync(resolve(root, path), { force: true });
    throw error;
  }
}

export function rebuildGeneratedProjection(root: string): void {
  for (const operation of planGeneratedProjection(root)) {
    // Generated files live in the repository too, so neither the delete nor the write may be
    // redirected through a committed symlink. `rm` does not follow a final symlink (a stale link is
    // simply removed), so a delete only needs link-free parent directories.
    if (operation.operation === "delete_entity") {
      assertPathHasNoSymlinkSegments(root, dirname(operation.path));
      rmSync(resolve(root, operation.path), { force: true });
    } else {
      writeFileWithoutFollowingSymlinks({ root, path: operation.path, body: withTrailingNewline(operation.body), expectedHash: operation.expectedHash });
    }
  }
}

export function planGeneratedProjection(root: string): GeneratedProjectionOperation[] {
  const desiredBody = GENERATED_ARCHITECTURE_BODY;
  const desiredAbsolute = resolve(root, GENERATED_ARCHITECTURE_PATH);
  const operations: GeneratedProjectionOperation[] = [];
  if (!existsSync(desiredAbsolute) || readFileSync(desiredAbsolute, "utf8") !== desiredBody) {
    operations.push({
      path: GENERATED_ARCHITECTURE_PATH,
      expectedHash: existsSync(desiredAbsolute) ? digestJson({ body: readFileSync(desiredAbsolute, "utf8") }) : "missing",
      body: desiredBody,
      operation: "render_projection"
    });
  }
  for (const path of collectGeneratedProjectionFiles(root)) {
    if (path === GENERATED_ARCHITECTURE_PATH) continue;
    const body = readFileSync(resolve(root, path), "utf8");
    operations.push({
      path,
      expectedHash: digestJson({ body }),
      body: "",
      operation: "delete_entity"
    });
  }
  return operations.sort((left, right) => left.path.localeCompare(right.path));
}

function collectGeneratedProjectionFiles(root: string): string[] {
  const generatedRoot = ".archcontext/generated";
  if (!existsSync(resolve(root, generatedRoot))) return [];
  const walk = (relativeDir: string): string[] => readdirSync(resolve(root, relativeDir), { withFileTypes: true })
    .flatMap((entry) => {
      const child = `${relativeDir}/${entry.name}`;
      if (entry.isDirectory()) return walk(child);
      return entry.isFile() ? [child] : [];
    });
  return walk(generatedRoot).sort();
}

export class YamlModelStore implements ModelStorePort {
  async loadManifest(workspace: WorkspaceRef): Promise<unknown> {
    return readFileSync(resolve(workspace.root, ".archcontext/manifest.yaml"), "utf8");
  }

  async loadModel(workspace: WorkspaceRef): Promise<ModelFile[]> {
    return listModelFiles(workspace.root);
  }

  async validateModel(workspace: WorkspaceRef): Promise<ModelValidationResult> {
    const errors: string[] = [];
    for (const required of [".archcontext/manifest.yaml", ".archcontext/product.yaml"]) {
      try {
        readFileSync(resolve(workspace.root, required), "utf8");
      } catch {
        errors.push(`missing ${required}`);
      }
    }
    const files = listModelFiles(workspace.root);
    for (const file of files) {
      if (!file.schemaVersion.startsWith("archcontext.")) errors.push(`${file.path}: missing schemaVersion`);
      if (file.path.startsWith(".archcontext/model/nodes/") && file.schemaVersion !== "archcontext.node/v2") {
        errors.push(`${file.path}: expected archcontext.node/v2, got ${file.schemaVersion || "missing"}`);
      }
      if (file.path.startsWith(".archcontext/model/flows/") && file.schemaVersion !== "archcontext.flow/v1") {
        errors.push(`${file.path}: expected archcontext.flow/v1, got ${file.schemaVersion || "missing"}`);
      }
    }
    const adr = validateAdrAppliesTo(files);
    errors.push(...adr.errors);
    const referenceErrors = adr.referenceErrors;
    const modelDigest = digestJson(files.map((file) => ({ path: file.path, digest: file.digest })));
    return { valid: errors.length === 0, errors, ...(referenceErrors.length > 0 ? { referenceErrors } : {}), modelDigest };
  }

  async writeChangeSetPreview(changeSet: unknown): Promise<{ digest: string; summary: string }> {
    return { digest: digestJson(changeSet as Json), summary: "ChangeSet preview generated" };
  }
}

export function listModelFiles(root: string): ModelFile[] {
  const paths = collectArchContextFiles(root, [
    ".archcontext/manifest.yaml",
    ".archcontext/product.yaml",
    ".archcontext/model",
    ".archcontext/decisions",
    ".archcontext/policies",
    ".archcontext/practices",
    ".archcontext/projections",
    ".archcontext/generated",
    "docs/adr"
  ]);
  return paths.map((path) => {
    const body = readFileSync(resolve(root, path), "utf8");
    return {
      path,
      body,
      schemaVersion: extractSchemaVersion(body),
      digest: digestJson({ path, body })
    };
  });
}

function collectArchContextFiles(root: string, entries: string[]): string[] {
  const files: string[] = [];
  for (const entry of entries) {
    const absolute = resolve(root, entry);
    if (!existsSync(absolute)) continue;
    const stat = readdirOrFile(absolute);
    if (stat === "file") {
      files.push(entry);
      continue;
    }
    for (const child of walk(entry)) files.push(child);
  }
  return [...new Set(files)].sort();

  function walk(relativeDir: string): string[] {
    const out: string[] = [];
    const dir = resolve(root, relativeDir);
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const child = `${relativeDir}/${entry.name}`;
      if (entry.isDirectory()) out.push(...walk(child));
      if (entry.isFile() && /\.(ya?ml|md)$/.test(entry.name) && isCollectableModelFile(child)) out.push(child);
    }
    return out;
  }
}

function isCollectableModelFile(path: string): boolean {
  if (path.startsWith("docs/adr/")) return /^docs\/adr\/ADR-\d{4}-.+\.md$/.test(path);
  return true;
}

function readdirOrFile(path: string): "directory" | "file" {
  try {
    readdirSync(path);
    return "directory";
  } catch {
    return "file";
  }
}

function extractSchemaVersion(body: string): string {
  const match = body.match(/schemaVersion:\s*"?([^"\n]+)"?/);
  if (match) return match[1].trim();
  try {
    const parsed = JSON.parse(body) as { schemaVersion?: unknown };
    if (typeof parsed.schemaVersion === "string") return parsed.schemaVersion;
  } catch {
    // JSON-compatible YAML is optional; plain YAML remains supported above.
  }
  if (body.includes("Generated by ArchContext")) return "archcontext.generated/v1";
  return "";
}

function withTrailingNewline(body: string): string {
  return body.endsWith("\n") ? body : `${body}\n`;
}

function lstatIfExists(path: string) {
  try {
    return lstatSync(path);
  } catch {
    return undefined;
  }
}
