import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeArchContextModel, rebuildGeneratedProjection } from "../../../local-runtime/model-store-yaml/src/index";
import { assertNoHumanEditableGeneratedSection, reconcileCrossRepoEvidence, reconcileGeneratedProjection } from "../src/index";

const projection = { rebuildGeneratedProjection };

describe("@archcontext/core/reconcile-engine", () => {
  test("rebuilds generated projection when no human section exists", () => {
      const root = mkdtempSync(join(tmpdir(), "archctx-reconcile-"));
    try {
      initializeArchContextModel(root, "Reconcile Test");
      expect(reconcileGeneratedProjection(root, projection)).toEqual({ rebuilt: true, preservedHumanSections: true });
      expect(readFileSync(join(root, ".archcontext/generated/ARCHITECTURE.md"), "utf8")).toContain("Generated by ArchContext");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("refuses to overwrite human-editable generated sections", () => {
    const root = mkdtempSync(join(tmpdir(), "archctx-reconcile-"));
    try {
      initializeArchContextModel(root, "Reconcile Test");
      writeFileSync(join(root, ".archcontext/generated/ARCHITECTURE.md"), "<!-- BEGIN HUMAN -->\nmanual note\n", "utf8");
      expect(() => assertNoHumanEditableGeneratedSection(root)).toThrow("human-editable");
      expect(() => reconcileGeneratedProjection(root, projection)).toThrow("human-editable");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("reconciles declared cross-repo relation with observed repository evidence", () => {
    const relation = {
      schemaVersion: "archcontext.cross-repo-relation/v1" as const,
      id: "relation.web-calls-api",
      kind: "calls" as const,
      source: { repositoryId: "repo.web", nodeId: "module.checkout-ui" },
      target: { repositoryId: "repo.api", nodeId: "module.billing-api" },
      via: { kind: "interface" as const, id: "interface.billing-http" },
      intent: "checkout to billing"
    };
    const result = reconcileCrossRepoEvidence({
      declared: [relation],
      observed: [
        {
          id: "evidence.web",
          selector: { path: "src/web.ts" },
          summary: "web caller",
          confidence: "observed",
          snapshot: { repositoryId: "repo.web", headSha: "abc", worktreeDigest: "sha256:web" }
        },
        {
          id: "evidence.api",
          selector: { path: "src/api.ts" },
          summary: "api callee",
          confidence: "observed",
          snapshot: { repositoryId: "repo.api", headSha: "def", worktreeDigest: "sha256:api" }
        }
      ]
    });
    expect(result.verified).toEqual(["relation.web-calls-api"]);
    expect(result.missingEvidence).toEqual([]);
  });
});
