import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initializeArchContextModel, rebuildGeneratedProjection } from "../../../local-runtime/model-store-yaml/src/index";
import { assertNoHumanEditableGeneratedSection, reconcileArchitectureLedgerDrift, reconcileCrossRepoEvidence, reconcileGeneratedProjection } from "../src/index";

const projection = { rebuildGeneratedProjection };

describe("@archcontext/core/reconcile-engine", () => {
  test("rebuilds generated projection when no human section exists", () => {
    const root = mkdtempSync(join(tmpdir(), "archctx-reconcile-"));
    try {
      initializeArchContextModel(root, "Reconcile Test");
      expect(reconcileGeneratedProjection(root, projection)).toEqual({ rebuilt: true, preservedHumanSections: true });
      expect(readFileSync(join(root, ".archcontext/generated/ARCHITECTURE.md"), "utf8")).toContain("Generated by ArchContext");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("refuses to overwrite human-editable generated sections", () => {
    const root = mkdtempSync(join(tmpdir(), "archctx-reconcile-"));
    try {
      initializeArchContextModel(root, "Reconcile Test");
      writeFileSync(join(root, ".archcontext/generated/ARCHITECTURE.md"), "<!-- BEGIN HUMAN -->\nmanual note\n", "utf8");
      expect(() => assertNoHumanEditableGeneratedSection(root)).toThrow("human-editable");
      expect(() => reconcileGeneratedProjection(root, projection)).toThrow("human-editable");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("reconciles declared cross-repo relation with observed repository evidence", () => {
    const relation = {
      schemaVersion: "archcontext.cross-repo-relation/v1" as const,
      id: "relation.web-calls-api",
      kind: "calls" as const,
      source: { repositoryId: "repo.web", nodeId: "module.checkout-ui" },
      target: { repositoryId: "repo.api", nodeId: "module.billing-api" },
      via: { kind: "interface" as const, id: "interface.billing-http" },
      intent: "checkout to billing"
    };
    const result = reconcileCrossRepoEvidence({
      declared: [relation],
      observed: [
        {
          id: "evidence.web",
          selector: { path: "src/web.ts" },
          summary: "web caller",
          confidence: "observed",
          snapshot: { repositoryId: "repo.web", headSha: "abc", worktreeDigest: "sha256:web" }
        },
        {
          id: "evidence.api",
          selector: { path: "src/api.ts" },
          summary: "api callee",
          confidence: "observed",
          snapshot: { repositoryId: "repo.api", headSha: "def", worktreeDigest: "sha256:api" }
        }
      ]
    });
    expect(result.verified).toEqual(["relation.web-calls-api"]);
    expect(result.missingEvidence).toEqual([]);
  });

  test("maps clean architecture ledger drift into a bidirectional reconcile report", () => {
    const report = reconcileArchitectureLedgerDrift({
      drift: {
        schemaVersion: "archcontext.architecture-ledger-drift/v1",
        ok: true,
        semanticDrift: false,
        sourceGraphDigest: "sha256:ledger",
        projectedGraphDigest: "sha256:ledger",
        projectionDigest: "sha256:projection",
        reasonCodes: [],
        unsupportedFiles: [],
        ignoredFiles: [],
        projectionDiffs: []
      }
    });

    expect(report).toMatchObject({
      schemaVersion: "archcontext.architecture-ledger-reconcile/v1",
      ok: true,
      reconcileRequired: false,
      reasonCodes: [],
      ledgerToGit: {
        direction: "ledger-to-git-projection",
        ok: true,
        status: "clean",
        sourceGraphDigest: "sha256:ledger",
        expectedProjectionDigest: "sha256:projection",
        diffCount: 0
      },
      gitToLedger: {
        direction: "git-to-ledger-state",
        ok: true,
        status: "clean",
        sourceGraphDigest: "sha256:ledger",
        targetGraphDigest: "sha256:ledger",
        unsupportedFileCount: 0
      },
      reconcileActions: []
    });
  });

  test("separates ledger-to-Git projection drift from Git-to-ledger semantic drift", () => {
    const report = reconcileArchitectureLedgerDrift({
      drift: {
        schemaVersion: "archcontext.architecture-ledger-drift/v1",
        ok: false,
        semanticDrift: true,
        sourceGraphDigest: "sha256:ledger",
        projectedGraphDigest: "sha256:git-yaml",
        projectionDigest: "sha256:ledger-projection",
        reasonCodes: ["projection-file-missing", "semantic-drift", "unsupported-yaml-file"],
        unsupportedFiles: [{
          path: ".archcontext/model/nodes/module.bad.yaml",
          schemaVersion: "archcontext.node/v1",
          reasonCode: "parse-error",
          message: "expected object"
        }],
        ignoredFiles: [],
        projectionDiffs: [{
          path: ".archcontext/model/nodes/module.checkout.yaml",
          reasonCode: "projection-file-missing",
          expectedDigest: "sha256:expected",
          targetKind: "entity",
          targetId: "module.checkout"
        }]
      }
    });

    expect(report.ok).toBe(false);
    expect(report.reconcileRequired).toBe(true);
    expect(report.reasonCodes).toEqual(["projection-file-missing", "semantic-drift", "unsupported-yaml-file"]);
    expect(report.ledgerToGit).toMatchObject({
      ok: false,
      status: "drift",
      sourceGraphDigest: "sha256:ledger",
      expectedProjectionDigest: "sha256:ledger-projection",
      reasonCodes: ["projection-file-missing"],
      diffCount: 1
    });
    expect(report.gitToLedger).toMatchObject({
      ok: false,
      status: "drift",
      sourceGraphDigest: "sha256:git-yaml",
      targetGraphDigest: "sha256:ledger",
      reasonCodes: ["semantic-drift", "unsupported-yaml-file"],
      unsupportedFileCount: 1
    });
    expect(report.reconcileActions.map((action) => action.kind)).toEqual([
      "fix-unsupported-yaml",
      "rebuild-ledger-from-git",
      "project-ledger-to-git"
    ]);
    expect(report.reconcileActions.map((action) => action.authority)).toEqual(["manual", "git-yaml", "ledger"]);
  });

  test("preserves raw drift reason codes not yet split into a direction", () => {
    const report = reconcileArchitectureLedgerDrift({
      drift: {
        schemaVersion: "archcontext.architecture-ledger-drift/v1",
        ok: false,
        semanticDrift: false,
        sourceGraphDigest: "sha256:ledger",
        projectedGraphDigest: "sha256:ledger",
        projectionDigest: "sha256:projection",
        reasonCodes: ["future-drift-reason"],
        unsupportedFiles: [],
        ignoredFiles: [],
        projectionDiffs: []
      }
    });

    expect(report.ok).toBe(false);
    expect(report.reconcileRequired).toBe(true);
    expect(report.reasonCodes).toEqual(["future-drift-reason"]);
    expect(report.ledgerToGit.ok).toBe(true);
    expect(report.gitToLedger.ok).toBe(true);
  });
});
