import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { digestJson, validateJsonSchema } from "../../contracts/src/index";
import { initializeArchContextModel } from "../../model-store-yaml/src/index";
import { ChangeSetEngine } from "../src/index";

const root = new URL("../../../", import.meta.url).pathname;
const digest = `sha256:${"a".repeat(64)}`;

function readJson(path: string) {
  return JSON.parse(readFileSync(join(root, path), "utf8"));
}

function tempModelRoot(): string {
  const dir = mkdtempSync(join(tmpdir(), "archctx-changeset-"));
  initializeArchContextModel(dir, "ChangeSet Test");
  return dir;
}

describe("@archcontext/changeset-engine", () => {
  test("plans schema-valid changesets and previews allowlist findings", () => {
    const engine = new ChangeSetEngine();
    const draft = engine.plan({
      id: "changeset.test",
      base: { headSha: "abc", worktreeDigest: digest, modelDigest: digest },
      reason: { taskSessionId: "task.test" },
      operations: [{ op: "write_policy", path: ".archcontext/policies/new.yaml", expectedHash: "missing", body: "schemaVersion: archcontext.policy/v1\n" }]
    });

    expect(validateJsonSchema(readJson("schemas/runtime/changeset.schema.json") as any, draft as any).valid).toBe(true);
    expect(engine.preview("/tmp/repo", draft)).toMatchObject({ allowed: true, paths: [".archcontext/policies/new.yaml"] });

    const denied = engine.plan({
      id: "changeset.denied",
      base: { headSha: "abc", worktreeDigest: digest, modelDigest: digest },
      reason: { taskSessionId: "task.test" },
      operations: [{ op: "write_policy", path: "src/app.ts", expectedHash: "missing", body: "" }]
    });
    expect(engine.preview("/tmp/repo", denied).allowed).toBe(false);
  });

  test("applies approved changes and rebuilds generated projection", async () => {
    const modelRoot = tempModelRoot();
    try {
      const engine = new ChangeSetEngine();
      const draft = engine.approve(
        engine.plan({
          id: "changeset.apply",
          base: { headSha: "abc", worktreeDigest: digest, modelDigest: digest },
          reason: { taskSessionId: "task.test", interventionId: "intervention.test" },
          operations: [
            {
              op: "write_policy",
              path: ".archcontext/policies/compatibility.yaml",
              expectedHash: "missing",
              body: "schemaVersion: archcontext.policy/v1\nid: policy.compatibility\n"
            }
          ]
        })
      );

      await expect(new ChangeSetEngine().apply(modelRoot, draft)).resolves.toMatchObject({ status: "applied" });
      expect(readFileSync(join(modelRoot, ".archcontext/policies/compatibility.yaml"), "utf8")).toContain("policy.compatibility");
      expect(readFileSync(join(modelRoot, ".archcontext/generated/ARCHITECTURE.md"), "utf8")).toContain("Generated by ArchContext");
    } finally {
      rmSync(modelRoot, { recursive: true, force: true });
    }
  });

  test("rolls back file writes when apply is interrupted", async () => {
    const modelRoot = tempModelRoot();
    try {
      const original = readFileSync(join(modelRoot, ".archcontext/policies/review.yaml"), "utf8");
      const engine = new ChangeSetEngine();
      const draft = engine.approve(
        engine.plan({
          id: "changeset.rollback",
          base: { headSha: "abc", worktreeDigest: digest, modelDigest: digest },
          reason: { taskSessionId: "task.test" },
          operations: [
            {
              op: "update_entity_fields",
              path: ".archcontext/policies/review.yaml",
              expectedHash: digestJson({ body: original }),
              body: "schemaVersion: archcontext.policy/v1\nid: policy.changed\n"
            }
          ]
        })
      );

      await expect(engine.apply(modelRoot, draft, { faultAfterOperations: 1 })).rejects.toThrow("fault-injection");
      expect(readFileSync(join(modelRoot, ".archcontext/policies/review.yaml"), "utf8")).toBe(original);
    } finally {
      rmSync(modelRoot, { recursive: true, force: true });
    }
  });

  test("requires approval before applying", async () => {
    const modelRoot = tempModelRoot();
    try {
      const engine = new ChangeSetEngine();
      const draft = engine.plan({
        id: "changeset.unapproved",
        base: { headSha: "abc", worktreeDigest: digest, modelDigest: digest },
        reason: { taskSessionId: "task.test" },
        operations: [{ op: "write_policy", path: ".archcontext/policies/new.yaml", expectedHash: "missing", body: "" }]
      });

      await expect(engine.apply(modelRoot, draft)).rejects.toThrow("approved");
    } finally {
      rmSync(modelRoot, { recursive: true, force: true });
    }
  });
});
