import { digestJson, stableId, type Json, type ModelExportResult } from "@archcontext/contracts";
import { stripAdapterProtectedNativeFields } from "@archcontext/core/architecture-domain";
import { normalizeNativeModel, type NativeModel, type NativeNode, type NativeRelation } from "@archcontext/surfaces/renderer";

export function exportLikeC4Model(model: NativeModel): ModelExportResult {
  const normalized = normalizeNativeModel(model);
  const lines = [
    "// Generated by ArchContext. Native model remains source of truth.",
    "specification {",
    "  element capability",
    "  element module",
    "  element component",
    "  element interface",
    "  element datastore",
    "  element external_system",
    "}",
    "",
    "model {"
  ];
  for (const node of normalized.nodes) {
    lines.push(`  // archctx-node ${JSON.stringify(node)}`);
    lines.push(`  ${likec4Id(node.id)} = ${likec4Kind(node.kind)} "${escapeDsl(node.name)}"`);
  }
  for (const relation of normalized.relations) {
    lines.push(`  // archctx-relation ${JSON.stringify(relation)}`);
    lines.push(`  ${likec4Id(relation.source)} -> ${likec4Id(relation.target)} "${escapeDsl(relation.kind)}"`);
  }
  lines.push("}", "", "views {", "  view index {", "    include *", "    autoLayout TopBottom", "  }", "}");
  const content = `${lines.join("\n")}\n`;
  return {
    format: "likec4",
    digest: digestJson({ format: "likec4", content } as unknown as Json),
    files: [{ path: ".archcontext/generated/architecture.likec4", content }]
  };
}

export function importLikeC4InitialModel(content: string): { nodes: NativeNode[]; relations: NativeRelation[]; warnings: string[] } {
  const nodes: NativeNode[] = [];
  const relations: NativeRelation[] = [];
  for (const line of content.split(/\r?\n/)) {
    const node = line.match(/^\s*\/\/ archctx-node (.+)$/);
    if (node) nodes.push(JSON.parse(node[1]) as NativeNode);
    const relation = line.match(/^\s*\/\/ archctx-relation (.+)$/);
    if (relation) relations.push(JSON.parse(relation[1]) as NativeRelation);
  }
  return {
    nodes: nodes.map((node) => stripAdapterProtectedNativeFields(node).clean),
    relations: relations.map((relation) => stripAdapterProtectedNativeFields(relation).clean) as NativeRelation[],
    warnings: ["LikeC4 import is initialization-only; Native ArchContext remains source of truth."]
  };
}

export function likec4Id(id: string): string {
  return stableId(id).replace(/-/g, "_").replace(/\./g, "_").replace(/::/g, "__");
}

function likec4Kind(kind: string): string {
  if (kind === "external-system") return "external_system";
  if (kind === "datastore") return "datastore";
  if (["capability", "module", "component", "interface"].includes(kind)) return kind;
  return "component";
}

function escapeDsl(value: string): string {
  return value.replace(/"/g, "'");
}
