import { describe, expect, test } from "bun:test";
import { architectureEventHash, digestJson, type Json } from "@archcontext/contracts";
import {
  ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
  architectureLedgerGitCursorFromPlan,
  architectureLedgerPayload,
  architectureLedgerStateDigest,
  compareArchitectureLedgerStateToYaml,
  planExternalProjectionChangeToArchitectureLedgerEvent,
  planGitCursorRefreshToArchitectureLedgerEvent,
  planYamlToArchitectureLedgerImport,
  projectArchitectureLedgerStateToYamlFiles,
  type ArchitectureLedgerModelFile,
  type ArchitectureLedgerScope
} from "../src/index";

const scope: ArchitectureLedgerScope = {
  repository: {
    repositoryId: "repo.yaml-ledger",
    storageRepositoryId: "repo.storage.yaml-ledger"
  },
  worktree: {
    workspaceId: "workspace.yaml-ledger",
    storageWorkspaceId: "workspace.storage.yaml-ledger",
    branch: "main",
    headSha: "abc123yaml",
    worktreeDigest: digestJson({ worktree: "yaml-ledger" } as unknown as Json)
  }
};

describe("@archcontext/core/architecture-ledger YAML bridge", () => {
  test("plans deterministic YAML import and projects back with zero semantic drift", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        "status: \"active\"",
        "summary: \"Serves checkout requests.\"",
        ""
      ]),
      modelFile(".archcontext/model/nodes/module.checkout.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.checkout\"",
        "kind: \"module\"",
        "name: \"Checkout\"",
        "status: \"active\"",
        "summary: \"Owns checkout orchestration.\"",
        ""
      ]),
      modelFile(".archcontext/model/relations/relation.checkout-api.yaml", [
        "schemaVersion: \"archcontext.relation/v1\"",
        "id: \"relation.checkout-api\"",
        "kind: \"calls\"",
        "source: \"module.checkout\"",
        "target: \"module.api\"",
        "intent: \"Checkout calls API.\"",
        ""
      ]),
      modelFile(".archcontext/model/constraints/constraint.api-owner.yaml", [
        "schemaVersion: \"archcontext.constraint/v1\"",
        "id: \"constraint.api-owner\"",
        "kind: \"owner-required\"",
        "subject: \"module.api\"",
        "severity: \"warning\"",
        "summary: \"API must have an owner.\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ]),
      modelFile(".archcontext/policies/review.yaml", [
        "schemaVersion: \"archcontext.policy/v1\"",
        "id: \"policy.review\"",
        "failOn:",
        "  - \"stale-context\"",
        ""
      ]),
      modelFile(".archcontext/generated/ARCHITECTURE.md", "<!-- Generated by ArchContext. Do not edit by hand. -->\n")
    ];

    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files: [...files].reverse(),
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const repeated = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:00:00.000Z"
    });

    expect(plan.graphDigest).toBe(repeated.graphDigest);
    expect(plan.sourceDigest).toBe(repeated.sourceDigest);
    expect(plan.event.eventHash).toBe(architectureEventHash(plan.event));
    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api", "module.checkout"]);
    expect(plan.state.relations.map((relation) => relation.relationId)).toEqual(["relation.checkout-api"]);
    expect(plan.state.constraints.map((constraint) => constraint.constraintId)).toEqual(["constraint.api-owner"]);
    expect(plan.imported).toContainEqual(expect.objectContaining({
      path: ".archcontext/policies/review.yaml",
      targetKind: "evidence"
    }));
    expect(plan.ignoredFiles).toEqual([{ path: ".archcontext/generated/ARCHITECTURE.md", reasonCode: "generated-projection" }]);
    expect(plan.unsupportedFiles).toEqual([]);
    expect(plan.drift).toMatchObject({ ok: true, semanticDrift: false, reasonCodes: [] });
    expect(plan.projectedFiles.map((file) => file.path)).toEqual([
      ".archcontext/model/constraints/constraint.api-owner.yaml",
      ".archcontext/model/nodes/module.api.yaml",
      ".archcontext/model/nodes/module.checkout.yaml",
      ".archcontext/model/relations/relation.checkout-api.yaml"
    ]);
    expect(architectureLedgerStateDigest(plan.state)).toBe(plan.drift.projectedGraphDigest);
    expect(projectArchitectureLedgerStateToYamlFiles(plan.state)[0]!.body).toContain("schemaVersion: \"archcontext.constraint/v1\"");
  });

  test("imports ADR frontmatter policies and manifest metadata as declared evidence without graph mutation", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        ""
      ]),
      modelFile("docs/adr/ADR-0040-hybrid-architecture-ledger.md", [
        "---",
        "schemaVersion: archcontext.adr/v1",
        "id: adr.0040.hybrid-architecture-ledger",
        "title: Hybrid Architecture Ledger",
        "status: accepted",
        "decidedAt: 2026-06-25",
        "appliesTo:",
        "  - package.local-runtime",
        "supersedes: []",
        "---",
        "",
        "# Private ADR body should not enter event payload",
        "",
        "The body may contain extended rationale, but the ledger import stores only digest-backed metadata."
      ]),
      modelFile(".archcontext/policies/review.yaml", [
        "schemaVersion: \"archcontext.policy/v1\"",
        "id: \"policy.review\"",
        "failOn:",
        "  - \"stale-context\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ])
    ];
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const changedAdr = planYamlToArchitectureLedgerImport({
      ...scope,
      files: files.map((file) => file.path === "docs/adr/ADR-0040-hybrid-architecture-ledger.md"
        ? modelFile(file.path, file.body.replace("Hybrid Architecture Ledger", "Hybrid Ledger Rename"))
        : file),
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const payload = architectureLedgerPayload(plan.event);

    expect(plan.unsupportedFiles).toEqual([]);
    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(changedAdr.graphDigest).toBe(plan.graphDigest);
    expect(changedAdr.sourceDigest).not.toBe(plan.sourceDigest);
    expect(plan.imported).toContainEqual({
      path: "docs/adr/ADR-0040-hybrid-architecture-ledger.md",
      schemaVersion: "archcontext.adr/v1",
      targetKind: "evidence",
      targetId: "adr.0040.hybrid-architecture-ledger"
    });
    expect(plan.imported).toContainEqual({
      path: ".archcontext/policies/review.yaml",
      schemaVersion: "archcontext.policy/v1",
      targetKind: "evidence",
      targetId: "policy.review"
    });
    expect(plan.imported).toContainEqual({
      path: ".archcontext/manifest.yaml",
      schemaVersion: "archcontext.manifest/v1",
      targetKind: "evidence",
      targetId: "product.checkout"
    });
    expect(payload.evidenceItems).toContainEqual(expect.objectContaining({
      subject: "adr.0040.hybrid-architecture-ledger",
      selector: expect.objectContaining({ path: "docs/adr/ADR-0040-hybrid-architecture-ledger.md" }),
      extensions: expect.objectContaining({
        declaredId: "adr.0040.hybrid-architecture-ledger",
        sourcePath: "docs/adr/ADR-0040-hybrid-architecture-ledger.md",
        schemaVersion: "archcontext.adr/v1"
      })
    }));
    expect(JSON.stringify(payload)).not.toContain("Private ADR body should not enter event payload");
  });

  test("preserves declared semantic IDs from legacy file paths and projects canonical paths", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/legacy_api_module.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          ""
        ]),
        modelFile(".archcontext/model/relations/legacy_checkout_api.yaml", [
          "schemaVersion: \"archcontext.relation/v1\"",
          "id: \"relation.checkout-api\"",
          "kind: \"calls\"",
          "source: \"module.checkout\"",
          "target: \"module.api\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.state.relations.map((relation) => relation.relationId)).toEqual(["relation.checkout-api"]);
    expect(plan.imported).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/legacy_api_module.yaml",
      targetKind: "entity",
      targetId: "module.api"
    }));
    expect(plan.projectedFiles.map((file) => file.path)).toEqual([
      ".archcontext/model/nodes/module.api.yaml",
      ".archcontext/model/relations/relation.checkout-api.yaml"
    ]);
    expect(plan.projectedFiles.map((file) => file.path)).not.toContain(".archcontext/model/nodes/legacy_api_module.yaml");
    expect(plan.drift.ok).toBe(true);
  });

  test("reports unsupported authoritative YAML without mutating supported graph facts", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ]),
        modelFile(".archcontext/model/custom/unknown.yaml", [
          "schemaVersion: \"archcontext.custom/v1\"",
          "id: \"custom.one\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.unsupportedFiles).toEqual([{
      path: ".archcontext/model/custom/unknown.yaml",
      schemaVersion: "archcontext.custom/v1",
      reasonCode: "unsupported-schema",
      message: ".archcontext/model/custom/unknown.yaml: unsupported architecture ledger YAML schema archcontext.custom/v1"
    }]);
    expect(plan.drift.ok).toBe(false);
    expect(plan.drift.reasonCodes).toEqual(["unsupported-yaml-file"]);
  });

  test("reports invalid authoritative YAML records without aborting dry-run import", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ]),
        modelFile(".archcontext/model/relations/relation.invalid.yaml", [
          "schemaVersion: \"archcontext.relation/v1\"",
          "id: \"relation.invalid\"",
          "kind: \"calls\"",
          "source: \"module.api\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.state.relations).toEqual([]);
    expect(plan.unsupportedFiles).toEqual([{
      path: ".archcontext/model/relations/relation.invalid.yaml",
      schemaVersion: "archcontext.relation/v1",
      reasonCode: "invalid-record",
      message: ".archcontext/model/relations/relation.invalid.yaml: target is required"
    }]);
    expect(plan.drift.ok).toBe(false);
    expect(plan.drift.reasonCodes).toEqual(["unsupported-yaml-file"]);
  });

  test("reports actionable ledger-to-Git projection drift reasons", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ]),
        modelFile(".archcontext/model/nodes/module.checkout.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.checkout\"",
          "kind: \"module\"",
          "name: \"Checkout\"",
          ""
        ])
      ]
    });

    const drift = compareArchitectureLedgerStateToYaml({
      state: plan.state,
      createdAt: "2026-06-25T02:01:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"Renamed API\"",
          ""
        ])
      ]
    });

    expect(drift.ok).toBe(false);
    expect(drift.reasonCodes).toEqual(["projection-file-digest-mismatch", "projection-file-missing", "semantic-drift"]);
    expect(drift.projectionDiffs).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/module.api.yaml",
      reasonCode: "projection-file-digest-mismatch"
    }));
    expect(drift.projectionDiffs).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/module.checkout.yaml",
      reasonCode: "projection-file-missing"
    }));
  });

  test("records a stable Git cursor without changing semantic state", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:02:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ])
      ]
    });
    const cursor = architectureLedgerGitCursorFromPlan({ ...scope, plan });
    const payload = architectureLedgerPayload(plan.event);
    expect(payload.sourceCursors).toContainEqual(expect.objectContaining({
      cursorId: ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
      source: "git",
      headSha: scope.worktree.headSha,
      cursorDigest: cursor.cursorDigest
    }));

    const refresh = planGitCursorRefreshToArchitectureLedgerEvent({
      ...scope,
      cursor,
      graphDigest: plan.graphDigest,
      createdAt: "2026-06-25T02:03:00.000Z"
    });
    const refreshPayload = architectureLedgerPayload(refresh.event);
    expect(refresh.event.eventType).toBe("architecture.git.cursor.refresh");
    expect(refresh.event.baseDigest).toBe(plan.graphDigest);
    expect(refresh.event.resultingDigest).toBe(plan.graphDigest);
    expect(refreshPayload.operations).toBeUndefined();
    expect(refreshPayload.sourceCursors).toContainEqual(expect.objectContaining({
      cursorId: ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
      cursorDigest: cursor.cursorDigest
    }));
  });

  test("plans external Git projection changes as proposed events requiring explicit reconcile", () => {
    const base = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:04:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ])
      ]
    });
    const proposal = planExternalProjectionChangeToArchitectureLedgerEvent({
      ...scope,
      previousState: base.state,
      createdAt: "2026-06-25T02:05:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"Renamed API\"",
          ""
        ])
      ]
    });
    const payload = architectureLedgerPayload(proposal.event);
    const external = payload as typeof payload & { proposedExternalProjectionChange?: Record<string, Json> };

    expect(proposal.event.eventType).toBe("architecture.projection.external_change.proposed");
    expect(proposal.event.baseDigest).toBe(base.graphDigest);
    expect(proposal.event.resultingDigest).toBe(base.graphDigest);
    expect(payload.operations).toBeUndefined();
    expect(payload.projectionState).toMatchObject({
      status: "external-change-proposed",
      reconcileRequired: true,
      baseGraphDigest: base.graphDigest,
      proposedGraphDigest: proposal.proposedGraphDigest
    });
    expect(external.proposedExternalProjectionChange?.reconcile).toMatchObject({
      required: true
    });
  });
});

function modelFile(path: string, lines: string[] | string): ArchitectureLedgerModelFile {
  const body = Array.isArray(lines) ? lines.join("\n") : lines;
  return {
    path,
    body,
    digest: digestJson({ path, body } as unknown as Json)
  };
}
