import { describe, expect, test } from "bun:test";
import { architectureEventHash, digestJson, type Json } from "@archcontext/contracts";
import {
  ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
  architectureLedgerGitCursorFromPlan,
  architectureLedgerPayload,
  architectureLedgerStateDigest,
  compareArchitectureLedgerStateToYaml,
  diffArchitectureLedgerBookStates,
  planExternalProjectionChangeToArchitectureLedgerEvent,
  planGitCursorRefreshToArchitectureLedgerEvent,
  planYamlToArchitectureLedgerImport,
  queryArchitectureLedgerBook,
  queryArchitectureLedgerBookEvidence,
  queryArchitectureLedgerBookNeighbors,
  queryArchitectureLedgerBookRecommendations,
  queryArchitectureLedgerBookTimeline,
  projectArchitectureLedgerStateToYamlFiles,
  showArchitectureLedgerBookSubject,
  type ArchitectureLedgerModelFile,
  type ArchitectureLedgerScope
} from "../src/index";

const scope: ArchitectureLedgerScope = {
  repository: {
    repositoryId: "repo.yaml-ledger",
    storageRepositoryId: "repo.storage.yaml-ledger"
  },
  worktree: {
    workspaceId: "workspace.yaml-ledger",
    storageWorkspaceId: "workspace.storage.yaml-ledger",
    branch: "main",
    headSha: "abc123yaml",
    worktreeDigest: digestJson({ worktree: "yaml-ledger" } as unknown as Json)
  }
};

describe("@archcontext/core/architecture-ledger YAML bridge", () => {
  test("plans deterministic YAML import and projects back with zero semantic drift", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        "status: \"active\"",
        "summary: \"Serves checkout requests.\"",
        ""
      ]),
      modelFile(".archcontext/model/nodes/module.checkout.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.checkout\"",
        "kind: \"module\"",
        "name: \"Checkout\"",
        "status: \"active\"",
        "summary: \"Owns checkout orchestration.\"",
        ""
      ]),
      modelFile(".archcontext/model/relations/relation.checkout-api.yaml", [
        "schemaVersion: \"archcontext.relation/v1\"",
        "id: \"relation.checkout-api\"",
        "kind: \"calls\"",
        "source: \"module.checkout\"",
        "target: \"module.api\"",
        "intent: \"Checkout calls API.\"",
        ""
      ]),
      modelFile(".archcontext/model/constraints/constraint.api-owner.yaml", [
        "schemaVersion: \"archcontext.constraint/v1\"",
        "id: \"constraint.api-owner\"",
        "kind: \"owner-required\"",
        "subject: \"module.api\"",
        "severity: \"warning\"",
        "summary: \"API must have an owner.\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ]),
      modelFile(".archcontext/policies/review.yaml", [
        "schemaVersion: \"archcontext.policy/v1\"",
        "id: \"policy.review\"",
        "failOn:",
        "  - \"stale-context\"",
        ""
      ]),
      modelFile(".archcontext/generated/ARCHITECTURE.md", "<!-- Generated by ArchContext. Do not edit by hand. -->\n")
    ];

    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files: [...files].reverse(),
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const repeated = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:00:00.000Z"
    });

    expect(plan.graphDigest).toBe(repeated.graphDigest);
    expect(plan.sourceDigest).toBe(repeated.sourceDigest);
    expect(plan.event.eventHash).toBe(architectureEventHash(plan.event));
    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api", "module.checkout"]);
    expect(plan.state.relations.map((relation) => relation.relationId)).toEqual(["relation.checkout-api"]);
    expect(plan.state.constraints.map((constraint) => constraint.constraintId)).toEqual(["constraint.api-owner"]);
    expect(plan.imported).toContainEqual(expect.objectContaining({
      path: ".archcontext/policies/review.yaml",
      targetKind: "evidence"
    }));
    expect(plan.ignoredFiles).toEqual([{ path: ".archcontext/generated/ARCHITECTURE.md", reasonCode: "generated-projection" }]);
    expect(plan.unsupportedFiles).toEqual([]);
    expect(plan.drift).toMatchObject({ ok: true, semanticDrift: false, reasonCodes: [] });
    expect(plan.projectedFiles.map((file) => file.path)).toEqual([
      ".archcontext/model/constraints/constraint.api-owner.yaml",
      ".archcontext/model/nodes/module.api.yaml",
      ".archcontext/model/nodes/module.checkout.yaml",
      ".archcontext/model/relations/relation.checkout-api.yaml"
    ]);
    expect(architectureLedgerStateDigest(plan.state)).toBe(plan.drift.projectedGraphDigest);
    expect(projectArchitectureLedgerStateToYamlFiles(plan.state)[0]!.body).toContain("schemaVersion: \"archcontext.constraint/v1\"");
  });

  test("queries Book state, neighbors, timeline, diff, evidence and recommendations with deterministic budgets", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        "status: \"active\"",
        "summary: \"Serves checkout requests.\"",
        ""
      ]),
      modelFile(".archcontext/model/nodes/module.checkout.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.checkout\"",
        "kind: \"module\"",
        "name: \"Checkout\"",
        "status: \"active\"",
        "summary: \"Owns checkout orchestration.\"",
        ""
      ]),
      modelFile(".archcontext/model/relations/relation.checkout-api.yaml", [
        "schemaVersion: \"archcontext.relation/v1\"",
        "id: \"relation.checkout-api\"",
        "kind: \"calls\"",
        "source: \"module.checkout\"",
        "target: \"module.api\"",
        "intent: \"Checkout calls API.\"",
        ""
      ]),
      modelFile(".archcontext/model/constraints/constraint.api-owner.yaml", [
        "schemaVersion: \"archcontext.constraint/v1\"",
        "id: \"constraint.api-owner\"",
        "kind: \"owner-required\"",
        "subject: \"module.api\"",
        "severity: \"warning\"",
        "summary: \"API must have an owner.\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ])
    ];
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:10:00.000Z"
    });
    const renamed = planYamlToArchitectureLedgerImport({
      ...scope,
      files: files.map((file) => file.path.endsWith("module.api.yaml")
        ? modelFile(file.path, file.body.replace("Serves checkout requests.", "Serves checkout and refund requests."))
        : file),
      createdAt: "2026-06-25T02:11:00.000Z"
    });
    const recommendationEvent = {
      ...plan.event,
      eventId: "architecture_event.recommendation",
      eventType: "architecture.recommendation.run",
      timestamp: "2026-06-25T02:12:00.000Z",
      payload: {
        recommendations: [{
          schemaVersion: "archcontext.recommendation/v1",
          recommendationId: "recommendation.api-owner",
          runId: "recommendation_run.one",
          fingerprint: "sha256:recommendation",
          subject: "module.api",
          status: "open",
          confidence: "medium",
          enforcement: "advisory",
          risk: "medium",
          uncertainty: "low",
          evidenceBindingIds: [],
          explanation: ["API has owner-required constraint evidence."],
          createdAt: "2026-06-25T02:12:00.000Z",
          updatedAt: "2026-06-25T02:12:00.000Z"
        }]
      }
    };
    const acceptedRecommendationEvent = {
      ...plan.event,
      eventId: "architecture_event.recommendation.lifecycle",
      eventType: "architecture.recommendation.lifecycle",
      timestamp: "2026-06-25T02:13:00.000Z",
      payload: {
        recommendations: [{
          schemaVersion: "archcontext.recommendation/v1",
          recommendationId: "recommendation.api-owner",
          runId: "recommendation_run.one",
          fingerprint: "sha256:recommendation",
          subject: "module.api",
          status: "accepted",
          confidence: "medium",
          enforcement: "advisory",
          risk: "medium",
          uncertainty: "low",
          evidenceBindingIds: [],
          explanation: ["API has owner-required constraint evidence."],
          createdAt: "2026-06-25T02:12:00.000Z",
          updatedAt: "2026-06-25T02:13:00.000Z"
        }]
      }
    };

    const query = queryArchitectureLedgerBook({ state: plan.state, events: [plan.event], query: "checkout", maxItems: 1, maxBytes: 4096 });
    expect(query.results.map((result) => result.id)).toEqual(["module.checkout"]);
    expect(query.results[0]?.scoreBreakdown.graphDistance).toBeGreaterThan(0);
    expect(query.results[0]?.scoreBreakdown.recency).toBeGreaterThan(0);
    expect(query.budget.truncated).toBe(true);
    expect(query.reasonCodes).toContain("item-budget-exceeded");

    const fallbackQuery = queryArchitectureLedgerBook({
      state: plan.state,
      events: [plan.event],
      query: "refund",
      explain: true,
      maxItems: 5,
      ftsMatches: [{
        targetKind: "evidence",
        targetId: "evidence.adr.refund-api",
        subjectId: "module.api",
        summary: "ADR summary says refund flow remains owned by the API module.",
        matchKind: "summary",
        score: 9,
        reasonCodes: ["sqlite-fts-match"]
      }]
    });
    expect(fallbackQuery.results[0]?.id).toBe("module.api");
    expect(fallbackQuery.results[0]?.scoreBreakdown.ftsFallback).toBeGreaterThan(0);
    expect(fallbackQuery.results[0]?.explanation?.reasonCodes).toContain("fts-fallback-match");
    expect(fallbackQuery.results[0]?.explanation?.fallbackMatches?.[0]).toMatchObject({
      targetKind: "evidence",
      targetId: "evidence.adr.refund-api",
      subjectId: "module.api"
    });

    const show = showArchitectureLedgerBookSubject(plan.state, "module.api");
    expect(show.subject?.summary).toBe("Serves checkout requests.");

    const neighbors = queryArchitectureLedgerBookNeighbors({ state: plan.state, id: "module.checkout", depth: 1, maxItems: 10 });
    expect(neighbors.nodes.map((node) => node.id)).toEqual(["module.checkout", "module.api"]);
    expect(neighbors.relations.map((relation) => relation.id)).toEqual(["relation.checkout-api"]);

    const timeline = queryArchitectureLedgerBookTimeline({ events: [plan.event], subjectId: "module.api", maxItems: 5 });
    expect(timeline.events[0]?.affectedSubjects).toEqual(expect.arrayContaining(["module.api", "relation.checkout-api"]));

    const diff = diffArchitectureLedgerBookStates({
      previousState: plan.state,
      nextState: renamed.state,
      fromRef: plan.event.eventId,
      toRef: renamed.event.eventId
    });
    expect(diff.summary.changed).toBe(1);
    expect(diff.changes).toContainEqual(expect.objectContaining({ id: "module.api", changeKind: "changed" }));
    expect(diff.changes[0]).toMatchObject({ evidenceIds: [], evidenceBindingIds: [] });

    const evidence = queryArchitectureLedgerBookEvidence({ events: [plan.event], id: "product.checkout" });
    expect(evidence.evidenceItems.length).toBeGreaterThan(0);
    expect(JSON.stringify(evidence)).not.toContain("Checkout calls API");

    const recommendations = queryArchitectureLedgerBookRecommendations({ events: [recommendationEvent as any], openOnly: true, explain: true });
    expect(recommendations.recommendations.map((recommendation) => recommendation.recommendationId)).toEqual(["recommendation.api-owner"]);
    expect(recommendations.explanations?.[0]).toMatchObject({
      targetKind: "recommendation",
      targetId: "recommendation.api-owner"
    });
    expect(recommendations.explanations?.[0]?.reasonCodes).toContain("open-recommendation-filter");

    const latestRecommendations = queryArchitectureLedgerBookRecommendations({
      events: [recommendationEvent as any, acceptedRecommendationEvent as any],
      explain: true
    });
    expect(latestRecommendations.recommendations).toHaveLength(1);
    expect(latestRecommendations.recommendations[0]?.status).toBe("accepted");
    const activeRecommendations = queryArchitectureLedgerBookRecommendations({
      events: [recommendationEvent as any, acceptedRecommendationEvent as any],
      openOnly: true
    });
    expect(activeRecommendations.recommendations).toEqual([]);
  });

  test("imports ADR frontmatter policies and manifest metadata as declared evidence without graph mutation", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        ""
      ]),
      modelFile("docs/adr/ADR-0040-hybrid-architecture-ledger.md", [
        "---",
        "schemaVersion: archcontext.adr/v1",
        "id: adr.0040.hybrid-architecture-ledger",
        "title: Hybrid Architecture Ledger",
        "status: accepted",
        "decidedAt: 2026-06-25",
        "appliesTo:",
        "  - package.local-runtime",
        "supersedes: []",
        "---",
        "",
        "# Private ADR body should not enter event payload",
        "",
        "The body may contain extended rationale, but the ledger import stores only digest-backed metadata."
      ]),
      modelFile(".archcontext/policies/review.yaml", [
        "schemaVersion: \"archcontext.policy/v1\"",
        "id: \"policy.review\"",
        "failOn:",
        "  - \"stale-context\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ])
    ];
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const changedAdr = planYamlToArchitectureLedgerImport({
      ...scope,
      files: files.map((file) => file.path === "docs/adr/ADR-0040-hybrid-architecture-ledger.md"
        ? modelFile(file.path, file.body.replace("Hybrid Architecture Ledger", "Hybrid Ledger Rename"))
        : file),
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const payload = architectureLedgerPayload(plan.event);

    expect(plan.unsupportedFiles).toEqual([]);
    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(changedAdr.graphDigest).toBe(plan.graphDigest);
    expect(changedAdr.sourceDigest).not.toBe(plan.sourceDigest);
    expect(plan.imported).toContainEqual({
      path: "docs/adr/ADR-0040-hybrid-architecture-ledger.md",
      schemaVersion: "archcontext.adr/v1",
      targetKind: "evidence",
      targetId: "adr.0040.hybrid-architecture-ledger"
    });
    expect(plan.imported).toContainEqual({
      path: ".archcontext/policies/review.yaml",
      schemaVersion: "archcontext.policy/v1",
      targetKind: "evidence",
      targetId: "policy.review"
    });
    expect(plan.imported).toContainEqual({
      path: ".archcontext/manifest.yaml",
      schemaVersion: "archcontext.manifest/v1",
      targetKind: "evidence",
      targetId: "product.checkout"
    });
    expect(payload.evidenceItems).toContainEqual(expect.objectContaining({
      subject: "adr.0040.hybrid-architecture-ledger",
      selector: expect.objectContaining({ path: "docs/adr/ADR-0040-hybrid-architecture-ledger.md" }),
      extensions: expect.objectContaining({
        declaredId: "adr.0040.hybrid-architecture-ledger",
        sourcePath: "docs/adr/ADR-0040-hybrid-architecture-ledger.md",
        schemaVersion: "archcontext.adr/v1"
      })
    }));
    expect(JSON.stringify(payload)).not.toContain("Private ADR body should not enter event payload");
  });

  test("preserves declared semantic IDs from legacy file paths and projects canonical paths", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/legacy_api_module.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          ""
        ]),
        modelFile(".archcontext/model/relations/legacy_checkout_api.yaml", [
          "schemaVersion: \"archcontext.relation/v1\"",
          "id: \"relation.checkout-api\"",
          "kind: \"calls\"",
          "source: \"module.checkout\"",
          "target: \"module.api\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.state.relations.map((relation) => relation.relationId)).toEqual(["relation.checkout-api"]);
    expect(plan.imported).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/legacy_api_module.yaml",
      targetKind: "entity",
      targetId: "module.api"
    }));
    expect(plan.projectedFiles.map((file) => file.path)).toEqual([
      ".archcontext/model/nodes/module.api.yaml",
      ".archcontext/model/relations/relation.checkout-api.yaml"
    ]);
    expect(plan.projectedFiles.map((file) => file.path)).not.toContain(".archcontext/model/nodes/legacy_api_module.yaml");
    expect(plan.drift.ok).toBe(true);
  });

  test("reports unsupported authoritative YAML without mutating supported graph facts", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ]),
        modelFile(".archcontext/model/custom/unknown.yaml", [
          "schemaVersion: \"archcontext.custom/v1\"",
          "id: \"custom.one\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.unsupportedFiles).toEqual([{
      path: ".archcontext/model/custom/unknown.yaml",
      schemaVersion: "archcontext.custom/v1",
      reasonCode: "unsupported-schema",
      message: ".archcontext/model/custom/unknown.yaml: unsupported architecture ledger YAML schema archcontext.custom/v1"
    }]);
    expect(plan.drift.ok).toBe(false);
    expect(plan.drift.reasonCodes).toEqual(["unsupported-yaml-file"]);
  });

  test("reports invalid authoritative YAML records without aborting dry-run import", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ]),
        modelFile(".archcontext/model/relations/relation.invalid.yaml", [
          "schemaVersion: \"archcontext.relation/v1\"",
          "id: \"relation.invalid\"",
          "kind: \"calls\"",
          "source: \"module.api\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.state.relations).toEqual([]);
    expect(plan.unsupportedFiles).toEqual([{
      path: ".archcontext/model/relations/relation.invalid.yaml",
      schemaVersion: "archcontext.relation/v1",
      reasonCode: "invalid-record",
      message: ".archcontext/model/relations/relation.invalid.yaml: target is required"
    }]);
    expect(plan.drift.ok).toBe(false);
    expect(plan.drift.reasonCodes).toEqual(["unsupported-yaml-file"]);
  });

  test("reports actionable ledger-to-Git projection drift reasons", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ]),
        modelFile(".archcontext/model/nodes/module.checkout.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.checkout\"",
          "kind: \"module\"",
          "name: \"Checkout\"",
          ""
        ])
      ]
    });

    const drift = compareArchitectureLedgerStateToYaml({
      state: plan.state,
      createdAt: "2026-06-25T02:01:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"Renamed API\"",
          ""
        ])
      ]
    });

    expect(drift.ok).toBe(false);
    expect(drift.reasonCodes).toEqual(["projection-file-digest-mismatch", "projection-file-missing", "semantic-drift"]);
    expect(drift.projectionDiffs).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/module.api.yaml",
      reasonCode: "projection-file-digest-mismatch"
    }));
    expect(drift.projectionDiffs).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/module.checkout.yaml",
      reasonCode: "projection-file-missing"
    }));
  });

  test("records a stable Git cursor without changing semantic state", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:02:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ])
      ]
    });
    const cursor = architectureLedgerGitCursorFromPlan({ ...scope, plan });
    const payload = architectureLedgerPayload(plan.event);
    expect(payload.sourceCursors).toContainEqual(expect.objectContaining({
      cursorId: ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
      source: "git",
      headSha: scope.worktree.headSha,
      cursorDigest: cursor.cursorDigest
    }));

    const refresh = planGitCursorRefreshToArchitectureLedgerEvent({
      ...scope,
      cursor,
      graphDigest: plan.graphDigest,
      createdAt: "2026-06-25T02:03:00.000Z"
    });
    const refreshPayload = architectureLedgerPayload(refresh.event);
    expect(refresh.event.eventType).toBe("architecture.git.cursor.refresh");
    expect(refresh.event.baseDigest).toBe(plan.graphDigest);
    expect(refresh.event.resultingDigest).toBe(plan.graphDigest);
    expect(refreshPayload.operations).toBeUndefined();
    expect(refreshPayload.sourceCursors).toContainEqual(expect.objectContaining({
      cursorId: ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
      cursorDigest: cursor.cursorDigest
    }));
  });

  test("plans external Git projection changes as proposed events requiring explicit reconcile", () => {
    const base = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:04:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          ""
        ])
      ]
    });
    const proposal = planExternalProjectionChangeToArchitectureLedgerEvent({
      ...scope,
      previousState: base.state,
      createdAt: "2026-06-25T02:05:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"Renamed API\"",
          ""
        ])
      ]
    });
    const payload = architectureLedgerPayload(proposal.event);
    const external = payload as typeof payload & { proposedExternalProjectionChange?: Record<string, Json> };

    expect(proposal.event.eventType).toBe("architecture.projection.external_change.proposed");
    expect(proposal.event.baseDigest).toBe(base.graphDigest);
    expect(proposal.event.resultingDigest).toBe(base.graphDigest);
    expect(payload.operations).toBeUndefined();
    expect(payload.projectionState).toMatchObject({
      status: "external-change-proposed",
      reconcileRequired: true,
      baseGraphDigest: base.graphDigest,
      proposedGraphDigest: proposal.proposedGraphDigest
    });
    expect(external.proposedExternalProjectionChange?.reconcile).toMatchObject({
      required: true
    });
  });
});

function modelFile(path: string, lines: string[] | string): ArchitectureLedgerModelFile {
  const body = Array.isArray(lines) ? lines.join("\n") : lines;
  return {
    path,
    body,
    digest: digestJson({ path, body } as unknown as Json)
  };
}
