import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseJsonOrStableYaml } from "@archcontext/core/architecture-domain";
import { architectureEventHash, digestJson, validateJsonSchema, type ArchitectureEventV1, type EvidenceBindingV1, type EvidenceItemV2, type Json } from "@archcontext/contracts";
import {
  ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
  architectureLedgerGitCursorFromPlan,
  architectureLedgerPayload,
  evidenceLifecycleValueDigest,
  architectureLedgerStateDigest,
  compareArchitectureLedgerStateToYaml,
  diffArchitectureLedgerBookStates,
  emptyArchitectureLedgerEvidenceState,
  planExternalProjectionChangeToArchitectureLedgerEvent,
  planGitCursorRefreshToArchitectureLedgerEvent,
  planYamlToArchitectureLedgerImport,
  queryArchitectureLedgerBook,
  queryArchitectureLedgerBookEvidence,
  queryArchitectureLedgerBookNeighbors,
  queryArchitectureLedgerBookRecommendations,
  queryArchitectureLedgerBookTimeline,
  projectArchitectureLedgerStateToYamlFiles,
  replayArchitectureLedgerEvidenceState,
  showArchitectureLedgerBookSubject,
  validateArchitectureLedgerEvent,
  ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION,
  type ArchitectureLedgerModelFile,
  type ArchitectureLedgerScope
} from "../src/index";

const scope: ArchitectureLedgerScope & { previousEvidenceState: ReturnType<typeof emptyArchitectureLedgerEvidenceState> } = {
  repository: {
    repositoryId: "repo.yaml-ledger",
    storageRepositoryId: "repo.storage.yaml-ledger"
  },
  worktree: {
    workspaceId: "workspace.yaml-ledger",
    storageWorkspaceId: "workspace.storage.yaml-ledger",
    branch: "main",
    headSha: "abc123yaml",
    worktreeDigest: digestJson({ worktree: "yaml-ledger" } as unknown as Json)
  },
  previousEvidenceState: emptyArchitectureLedgerEvidenceState()
};
const repositoryRoot = fileURLToPath(new URL("../../../../", import.meta.url));

describe("@archcontext/core/architecture-ledger YAML bridge", () => {
  test("rejects raw diff fields and secret-shaped values at the event persistence boundary", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T00:00:00.000Z",
      files: []
    });
    expect(() => validateArchitectureLedgerEvent({
      ...plan.event,
      payload: { rawDiff: "diff --git a/private.ts b/private.ts" }
    })).toThrow("architecture-ledger-privacy-denied");
    expect(() => validateArchitectureLedgerEvent({
      ...plan.event,
      payload: { summary: "token=super-secret-value" }
    })).toThrow("architecture-ledger-privacy-denied");
  });

  test("plans deterministic YAML import and projects back with zero semantic drift", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        "status: \"active\"",
        "summary: \"Serves checkout requests.\"",
        "responsibilities: [\"HTTP request handling\"]",
        "source:",
        "  include: [\"packages/api/**\"]",
        "ownership:",
        "  lifecycle: [\"team-api\"]",
        ""
      ]),
      modelFile(".archcontext/model/nodes/module.checkout.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.checkout\"",
        "kind: \"module\"",
        "name: \"Checkout\"",
        "status: \"active\"",
        "summary: \"Owns checkout orchestration.\"",
        ""
      ]),
      modelFile(".archcontext/model/relations/relation.checkout-api.yaml", [
        "schemaVersion: \"archcontext.relation/v1\"",
        "id: \"relation.checkout-api\"",
        "kind: \"calls\"",
        "source: \"module.checkout\"",
        "target: \"module.api\"",
        "protocol: \"HTTP\"",
        "intent: \"Checkout calls API.\"",
        ""
      ]),
      modelFile(".archcontext/model/constraints/constraint.api-owner.yaml", [
        "schemaVersion: \"archcontext.constraint/v1\"",
        "id: \"constraint.api-owner\"",
        "name: \"API owner required\"",
        "severity: \"warning\"",
        "scope:",
        "  nodes: [\"module.api\"]",
        "rule:",
        "  type: \"require-owner\"",
        "rationale: \"API must have an owner.\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ]),
      modelFile(".archcontext/policies/review.yaml", [
        "schemaVersion: \"archcontext.policy/v1\"",
        "id: \"policy.review\"",
        "failOn:",
        "  - \"stale-context\"",
        ""
      ]),
      modelFile(".archcontext/generated/ARCHITECTURE.md", "<!-- Generated by ArchContext. Do not edit by hand. -->\n")
    ];

    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files: [...files].reverse(),
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const repeated = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:00:00.000Z"
    });

    expect(plan.graphDigest).toBe(repeated.graphDigest);
    expect(plan.sourceDigest).toBe(repeated.sourceDigest);
    expect(plan.event.eventHash).toBe(architectureEventHash(plan.event));
    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api", "module.checkout"]);
    expect(plan.state.relations.map((relation) => relation.relationId)).toEqual(["relation.checkout-api"]);
    expect(plan.state.constraints.map((constraint) => constraint.constraintId)).toEqual(["constraint.api-owner"]);
    expect(plan.imported).toContainEqual(expect.objectContaining({
      path: ".archcontext/policies/review.yaml",
      targetKind: "evidence"
    }));
    expect(plan.ignoredFiles).toEqual([{ path: ".archcontext/generated/ARCHITECTURE.md", reasonCode: "generated-projection" }]);
    expect(plan.unsupportedFiles).toEqual([]);
    expect(plan.drift).toMatchObject({ ok: true, semanticDrift: false, reasonCodes: [] });
    expect(plan.projectedFiles.map((file) => file.path)).toEqual([
      ".archcontext/model/constraints/constraint.api-owner.yaml",
      ".archcontext/model/nodes/module.api.yaml",
      ".archcontext/model/nodes/module.checkout.yaml",
      ".archcontext/model/relations/relation.checkout-api.yaml"
    ]);
    expect(architectureLedgerStateDigest(plan.state)).toBe(plan.drift.projectedGraphDigest);
    expect(projectArchitectureLedgerStateToYamlFiles(plan.state)[0]!.body).toContain("schemaVersion: \"archcontext.constraint/v1\"");
    const projectedNode = plan.projectedFiles.find((file) => file.targetId === "module.api")!;
    expect(projectedNode.body).toContain("source:");
    expect(projectedNode.body).toContain("packages/api/**");
    expect(projectedNode.body).toContain("responsibilities:");
    const schemas = {
      entity: JSON.parse(readFileSync(`${repositoryRoot}/schemas/repo/architecture-node.schema.json`, "utf8")),
      relation: JSON.parse(readFileSync(`${repositoryRoot}/schemas/repo/architecture-relation.schema.json`, "utf8")),
      constraint: JSON.parse(readFileSync(`${repositoryRoot}/schemas/repo/constraint.schema.json`, "utf8"))
    };
    for (const file of plan.projectedFiles) {
      const parsed = parseJsonOrStableYaml(file.body, file.path);
      expect(validateJsonSchema(schemas[file.targetKind] as any, parsed).valid).toBe(true);
    }
  });

  test("queries Book state, neighbors, timeline, diff, evidence and recommendations with deterministic budgets", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        "status: \"active\"",
        "summary: \"Serves checkout requests.\"",
        ""
      ]),
      modelFile(".archcontext/model/nodes/module.checkout.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.checkout\"",
        "kind: \"module\"",
        "name: \"Checkout\"",
        "status: \"active\"",
        "summary: \"Owns checkout orchestration.\"",
        ""
      ]),
      modelFile(".archcontext/model/relations/relation.checkout-api.yaml", [
        "schemaVersion: \"archcontext.relation/v1\"",
        "id: \"relation.checkout-api\"",
        "kind: \"calls\"",
        "source: \"module.checkout\"",
        "target: \"module.api\"",
        "intent: \"Checkout calls API.\"",
        ""
      ]),
      modelFile(".archcontext/model/constraints/constraint.api-owner.yaml", [
        "schemaVersion: \"archcontext.constraint/v1\"",
        "id: \"constraint.api-owner\"",
        "name: \"API owner required\"",
        "severity: \"warning\"",
        "scope:",
        "  nodes: [\"module.api\"]",
        "rule:",
        "  type: \"require-owner\"",
        "rationale: \"API must have an owner.\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ])
    ];
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:10:00.000Z"
    });
    const renamed = planYamlToArchitectureLedgerImport({
      ...scope,
      files: files.map((file) => file.path.endsWith("module.api.yaml")
        ? modelFile(file.path, file.body.replace("Serves checkout requests.", "Serves checkout and refund requests."))
        : file),
      createdAt: "2026-06-25T02:11:00.000Z"
    });
    const recommendationEvent = {
      ...plan.event,
      eventId: "architecture_event.recommendation",
      eventType: "architecture.recommendation.run",
      timestamp: "2026-06-25T02:12:00.000Z",
      payload: {
        recommendations: [{
          schemaVersion: "archcontext.recommendation/v1",
          recommendationId: "recommendation.api-owner",
          runId: "recommendation_run.one",
          fingerprint: "sha256:recommendation",
          subject: "module.api",
          status: "open",
          confidence: "medium",
          enforcement: "advisory",
          risk: "medium",
          uncertainty: "low",
          evidenceBindingIds: [],
          explanation: ["API has owner-required constraint evidence."],
          createdAt: "2026-06-25T02:12:00.000Z",
          updatedAt: "2026-06-25T02:12:00.000Z"
        }]
      }
    };
    const acceptedRecommendationEvent = {
      ...plan.event,
      eventId: "architecture_event.recommendation.lifecycle",
      eventType: "architecture.recommendation.lifecycle",
      timestamp: "2026-06-25T02:13:00.000Z",
      payload: {
        recommendations: [{
          schemaVersion: "archcontext.recommendation/v1",
          recommendationId: "recommendation.api-owner",
          runId: "recommendation_run.one",
          fingerprint: "sha256:recommendation",
          subject: "module.api",
          status: "accepted",
          confidence: "medium",
          enforcement: "advisory",
          risk: "medium",
          uncertainty: "low",
          evidenceBindingIds: [],
          explanation: ["API has owner-required constraint evidence."],
          createdAt: "2026-06-25T02:12:00.000Z",
          updatedAt: "2026-06-25T02:13:00.000Z"
        }]
      }
    };

    const query = queryArchitectureLedgerBook({ state: plan.state, events: [plan.event], query: "checkout", maxItems: 1, maxBytes: 4096 });
    expect(query.results.map((result) => result.id)).toEqual(["module.checkout"]);
    expect(query.results[0]?.scoreBreakdown.graphDistance).toBeGreaterThan(0);
    expect(query.results[0]?.scoreBreakdown.recency).toBeGreaterThan(0);
    expect(query.budget.truncated).toBe(true);
    expect(query.reasonCodes).toContain("item-budget-exceeded");

    const fallbackQuery = queryArchitectureLedgerBook({
      state: plan.state,
      events: [plan.event],
      query: "refund",
      explain: true,
      maxItems: 5,
      ftsMatches: [{
        targetKind: "evidence",
        targetId: "evidence.adr.refund-api",
        subjectId: "module.api",
        summary: "ADR summary says refund flow remains owned by the API module.",
        matchKind: "summary",
        score: 9,
        reasonCodes: ["sqlite-fts-match"]
      }]
    });
    expect(fallbackQuery.results[0]?.id).toBe("module.api");
    expect(fallbackQuery.results[0]?.scoreBreakdown.ftsFallback).toBeGreaterThan(0);
    expect(fallbackQuery.results[0]?.explanation?.reasonCodes).toContain("fts-fallback-match");
    expect(fallbackQuery.results[0]?.explanation?.fallbackMatches?.[0]).toMatchObject({
      targetKind: "evidence",
      targetId: "evidence.adr.refund-api",
      subjectId: "module.api"
    });

    const show = showArchitectureLedgerBookSubject(plan.state, "module.api");
    expect(show.subject?.summary).toBe("Serves checkout requests.");

    const neighbors = queryArchitectureLedgerBookNeighbors({ state: plan.state, id: "module.checkout", depth: 1, maxItems: 10 });
    expect(neighbors.nodes.map((node) => node.id)).toEqual(["module.checkout", "module.api"]);
    expect(neighbors.relations.map((relation) => relation.id)).toEqual(["relation.checkout-api"]);

    const timeline = queryArchitectureLedgerBookTimeline({ events: [plan.event], subjectId: "module.api", maxItems: 5 });
    expect(timeline.events[0]?.affectedSubjects).toEqual(expect.arrayContaining(["module.api", "relation.checkout-api"]));

    const diff = diffArchitectureLedgerBookStates({
      previousState: plan.state,
      nextState: renamed.state,
      fromRef: plan.event.eventId,
      toRef: renamed.event.eventId
    });
    expect(diff.summary.changed).toBe(1);
    expect(diff.changes).toContainEqual(expect.objectContaining({ id: "module.api", changeKind: "changed" }));
    expect(diff.changes[0]).toMatchObject({ evidenceIds: [], evidenceBindingIds: [] });

    const evidence = queryArchitectureLedgerBookEvidence({ events: [plan.event], id: "product.checkout" });
    expect(evidence.evidenceItems.length).toBeGreaterThan(0);
    expect(JSON.stringify(evidence)).not.toContain("Checkout calls API");

    const recommendations = queryArchitectureLedgerBookRecommendations({ events: [recommendationEvent as any], openOnly: true, explain: true });
    expect(recommendations.recommendations.map((recommendation) => recommendation.recommendationId)).toEqual(["recommendation.api-owner"]);
    expect(recommendations.explanations?.[0]).toMatchObject({
      targetKind: "recommendation",
      targetId: "recommendation.api-owner"
    });
    expect(recommendations.explanations?.[0]?.reasonCodes).toContain("open-recommendation-filter");

    const latestRecommendations = queryArchitectureLedgerBookRecommendations({
      events: [recommendationEvent as any, acceptedRecommendationEvent as any],
      explain: true
    });
    expect(latestRecommendations.recommendations).toHaveLength(1);
    expect(latestRecommendations.recommendations[0]?.status).toBe("accepted");
    const activeRecommendations = queryArchitectureLedgerBookRecommendations({
      events: [recommendationEvent as any, acceptedRecommendationEvent as any],
      openOnly: true
    });
    expect(activeRecommendations.recommendations).toEqual([]);
  });

  test("imports ADR frontmatter policies and manifest metadata as declared evidence without graph mutation", () => {
    const files = [
      modelFile(".archcontext/model/nodes/module.api.yaml", [
        "schemaVersion: \"archcontext.node/v1\"",
        "id: \"module.api\"",
        "kind: \"module\"",
        "name: \"API\"",
        "status: \"active\"",
        "summary: \"Serves API requests.\"",
        ""
      ]),
      modelFile("docs/adr/ADR-0040-hybrid-architecture-ledger.md", [
        "---",
        "schemaVersion: archcontext.adr/v1",
        "id: adr.0040.hybrid-architecture-ledger",
        "title: Hybrid Architecture Ledger",
        "status: accepted",
        "decidedAt: 2026-06-25",
        "appliesTo:",
        "  - package.local-runtime",
        "supersedes: []",
        "---",
        "",
        "# Private ADR body should not enter event payload",
        "",
        "The body may contain extended rationale, but the ledger import stores only digest-backed metadata."
      ]),
      modelFile(".archcontext/policies/review.yaml", [
        "schemaVersion: \"archcontext.policy/v1\"",
        "id: \"policy.review\"",
        "failOn:",
        "  - \"stale-context\"",
        ""
      ]),
      modelFile(".archcontext/manifest.yaml", [
        "schemaVersion: \"archcontext.manifest/v1\"",
        "product:",
        "  id: \"product.checkout\"",
        "  name: \"Checkout\"",
        ""
      ])
    ];
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      files,
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const changedAdr = planYamlToArchitectureLedgerImport({
      ...scope,
      files: files.map((file) => file.path === "docs/adr/ADR-0040-hybrid-architecture-ledger.md"
        ? modelFile(file.path, file.body.replace("Hybrid Architecture Ledger", "Hybrid Ledger Rename"))
        : file),
      createdAt: "2026-06-25T02:00:00.000Z"
    });
    const payload = architectureLedgerPayload(plan.event);

    expect(plan.unsupportedFiles).toEqual([]);
    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(changedAdr.graphDigest).toBe(plan.graphDigest);
    expect(changedAdr.sourceDigest).not.toBe(plan.sourceDigest);
    expect(plan.imported).toContainEqual({
      path: "docs/adr/ADR-0040-hybrid-architecture-ledger.md",
      schemaVersion: "archcontext.adr/v1",
      targetKind: "evidence",
      targetId: "adr.0040.hybrid-architecture-ledger"
    });
    expect(plan.imported).toContainEqual({
      path: ".archcontext/policies/review.yaml",
      schemaVersion: "archcontext.policy/v1",
      targetKind: "evidence",
      targetId: "policy.review"
    });
    expect(plan.imported).toContainEqual({
      path: ".archcontext/manifest.yaml",
      schemaVersion: "archcontext.manifest/v1",
      targetKind: "evidence",
      targetId: "product.checkout"
    });
    expect(replayArchitectureLedgerEvidenceState([plan.event]).evidenceItems).toContainEqual(expect.objectContaining({
      subject: "adr.0040.hybrid-architecture-ledger",
      selector: expect.objectContaining({ path: "docs/adr/ADR-0040-hybrid-architecture-ledger.md" }),
      extensions: expect.objectContaining({
        declaredId: "adr.0040.hybrid-architecture-ledger",
        sourcePath: "docs/adr/ADR-0040-hybrid-architecture-ledger.md",
        schemaVersion: "archcontext.adr/v1"
      })
    }));
    expect(JSON.stringify(payload)).not.toContain("Private ADR body should not enter event payload");
  });

  test("preserves declared semantic IDs from legacy file paths and projects canonical paths", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/legacy_api_module.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ]),
        modelFile(".archcontext/model/relations/legacy_checkout_api.yaml", [
          "schemaVersion: \"archcontext.relation/v1\"",
          "id: \"relation.checkout-api\"",
          "kind: \"calls\"",
          "source: \"module.checkout\"",
          "target: \"module.api\"",
          "intent: \"Checkout calls API.\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.state.relations.map((relation) => relation.relationId)).toEqual(["relation.checkout-api"]);
    expect(plan.imported).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/legacy_api_module.yaml",
      targetKind: "entity",
      targetId: "module.api"
    }));
    expect(plan.projectedFiles.map((file) => file.path)).toEqual([
      ".archcontext/model/nodes/module.api.yaml",
      ".archcontext/model/relations/relation.checkout-api.yaml"
    ]);
    expect(plan.projectedFiles.map((file) => file.path)).not.toContain(".archcontext/model/nodes/legacy_api_module.yaml");
    expect(plan.drift.ok).toBe(true);
  });

  test("reports unsupported authoritative YAML without mutating supported graph facts", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ]),
        modelFile(".archcontext/model/custom/unknown.yaml", [
          "schemaVersion: \"archcontext.custom/v1\"",
          "id: \"custom.one\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.unsupportedFiles).toEqual([{
      path: ".archcontext/model/custom/unknown.yaml",
      schemaVersion: "archcontext.custom/v1",
      reasonCode: "unsupported-schema",
      message: ".archcontext/model/custom/unknown.yaml: unsupported architecture ledger YAML schema archcontext.custom/v1"
    }]);
    expect(plan.drift.ok).toBe(false);
    expect(plan.drift.reasonCodes).toEqual(["unsupported-yaml-file"]);
  });

  test("reports invalid authoritative YAML records without aborting dry-run import", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ]),
        modelFile(".archcontext/model/relations/relation.invalid.yaml", [
          "schemaVersion: \"archcontext.relation/v1\"",
          "id: \"relation.invalid\"",
          "kind: \"calls\"",
          "source: \"module.api\"",
          ""
        ])
      ]
    });

    expect(plan.state.entities.map((entity) => entity.entityId)).toEqual(["module.api"]);
    expect(plan.state.relations).toEqual([]);
    expect(plan.unsupportedFiles).toEqual([{
      path: ".archcontext/model/relations/relation.invalid.yaml",
      schemaVersion: "archcontext.relation/v1",
      reasonCode: "invalid-record",
      message: ".archcontext/model/relations/relation.invalid.yaml: target is required"
    }]);
    expect(plan.drift.ok).toBe(false);
    expect(plan.drift.reasonCodes).toEqual(["unsupported-yaml-file"]);
  });

  test("reports actionable ledger-to-Git projection drift reasons", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:00:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ]),
        modelFile(".archcontext/model/nodes/module.checkout.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.checkout\"",
          "kind: \"module\"",
          "name: \"Checkout\"",
          "status: \"active\"",
          "summary: \"Owns checkout orchestration.\"",
          ""
        ])
      ]
    });

    const drift = compareArchitectureLedgerStateToYaml({
      state: plan.state,
      createdAt: "2026-06-25T02:01:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"Renamed API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ])
      ]
    });

    expect(drift.ok).toBe(false);
    expect(drift.reasonCodes).toEqual(["projection-file-digest-mismatch", "projection-file-missing", "semantic-drift"]);
    expect(drift.projectionDiffs).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/module.api.yaml",
      reasonCode: "projection-file-digest-mismatch"
    }));
    expect(drift.projectionDiffs).toContainEqual(expect.objectContaining({
      path: ".archcontext/model/nodes/module.checkout.yaml",
      reasonCode: "projection-file-missing"
    }));
  });

  test("records a stable Git cursor without changing semantic state", () => {
    const plan = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:02:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ])
      ]
    });
    const cursor = architectureLedgerGitCursorFromPlan({ ...scope, plan });
    const payload = architectureLedgerPayload(plan.event);
    expect(payload.sourceCursors).toContainEqual(expect.objectContaining({
      cursorId: ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
      source: "git",
      headSha: scope.worktree.headSha,
      cursorDigest: cursor.cursorDigest
    }));

    const refresh = planGitCursorRefreshToArchitectureLedgerEvent({
      ...scope,
      cursor,
      graphDigest: plan.graphDigest,
      createdAt: "2026-06-25T02:03:00.000Z"
    });
    const refreshPayload = architectureLedgerPayload(refresh.event);
    expect(refresh.event.eventType).toBe("architecture.git.cursor.refresh");
    expect(refresh.event.baseDigest).toBe(plan.graphDigest);
    expect(refresh.event.resultingDigest).toBe(plan.graphDigest);
    expect(refreshPayload.operations).toBeUndefined();
    expect(refreshPayload.sourceCursors).toContainEqual(expect.objectContaining({
      cursorId: ARCHITECTURE_LEDGER_GIT_CURSOR_ID,
      cursorDigest: cursor.cursorDigest
    }));
  });

  test("plans external Git projection changes as proposed events requiring explicit reconcile", () => {
    const base = planYamlToArchitectureLedgerImport({
      ...scope,
      createdAt: "2026-06-25T02:04:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"API\"",
          "status: \"active\"",
          "summary: \"Serves API requests.\"",
          ""
        ])
      ]
    });
    const proposal = planExternalProjectionChangeToArchitectureLedgerEvent({
      ...scope,
      previousState: base.state,
      createdAt: "2026-06-25T02:05:00.000Z",
      files: [
        modelFile(".archcontext/model/nodes/module.api.yaml", [
          "schemaVersion: \"archcontext.node/v1\"",
          "id: \"module.api\"",
          "kind: \"module\"",
          "name: \"Renamed API\"",
          "status: \"active\"",
          "summary: \"Serves renamed API requests.\"",
          ""
        ])
      ]
    });
    const payload = architectureLedgerPayload(proposal.event);
    const external = payload as typeof payload & { proposedExternalProjectionChange?: Record<string, Json> };

    expect(proposal.event.eventType).toBe("architecture.projection.external_change.proposed");
    expect(proposal.event.baseDigest).toBe(base.graphDigest);
    expect(proposal.event.resultingDigest).toBe(base.graphDigest);
    expect(payload.operations).toBeUndefined();
    expect(payload.projectionState).toMatchObject({
      status: "external-change-proposed",
      reconcileRequired: true,
      baseGraphDigest: base.graphDigest,
      proposedGraphDigest: proposal.proposedGraphDigest
    });
    expect(external.proposedExternalProjectionChange?.reconcile).toMatchObject({
      required: true
    });
  });
});

describe("@archcontext/core/architecture-ledger evidence lifecycle", () => {
  test("replays explicit create update remove operations with durable tombstones", () => {
    const itemV1 = evidenceItem("Owns API");
    const itemV2 = evidenceItem("Owns API and routing");
    const binding = evidenceBinding(itemV1.evidenceId);
    const create = evidenceEvent("create", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [
        { target: "item", action: "create", evidenceId: itemV1.evidenceId, value: itemV1 },
        { target: "binding", action: "create", bindingId: binding.bindingId, value: binding }
      ]
    });
    const update = evidenceEvent("update", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [{
        target: "item",
        action: "update",
        evidenceId: itemV1.evidenceId,
        previousDigest: evidenceLifecycleValueDigest(itemV1),
        value: itemV2
      }]
    });
    const remove = evidenceEvent("remove", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [
        { target: "binding", action: "remove", bindingId: binding.bindingId, previousDigest: evidenceLifecycleValueDigest(binding), reasonCode: "superseded" },
        { target: "item", action: "remove", evidenceId: itemV2.evidenceId, previousDigest: evidenceLifecycleValueDigest(itemV2), reasonCode: "superseded" }
      ]
    });

    const afterUpdate = replayArchitectureLedgerEvidenceState([create, update]);
    expect(afterUpdate.evidenceItems).toEqual([itemV2]);
    expect(afterUpdate.evidenceBindings).toEqual([binding]);
    expect(afterUpdate.tombstones).toEqual([]);

    const afterRemove = replayArchitectureLedgerEvidenceState([create, update, remove]);
    expect(afterRemove.evidenceItems).toEqual([]);
    expect(afterRemove.evidenceBindings).toEqual([]);
    expect(afterRemove.tombstones.map((item) => `${item.target}:${item.id}`)).toEqual([
      `binding:${binding.bindingId}`,
      `item:${itemV2.evidenceId}`
    ]);
    expect(afterRemove.stateDigest).toMatch(/^sha256:[a-f0-9]{64}$/);
  });

  test("fails closed on illegal lifecycle transitions", () => {
    const item = evidenceItem("Owns API");
    const create = evidenceEvent("create", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [{ target: "item", action: "create", evidenceId: item.evidenceId, value: item }]
    });
    const badUpdate = evidenceEvent("bad-update", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [{
        target: "item",
        action: "update",
        evidenceId: item.evidenceId,
        previousDigest: digestJson({ wrong: true } as unknown as Json),
        value: evidenceItem("Changed")
      }]
    });
    expect(() => replayArchitectureLedgerEvidenceState([create, badUpdate])).toThrow("previous-digest-mismatch");

    const binding = evidenceBinding(item.evidenceId);
    const missingItemBinding = evidenceEvent("missing-item", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [{ target: "binding", action: "create", bindingId: binding.bindingId, value: binding }]
    });
    expect(() => replayArchitectureLedgerEvidenceState([missingItemBinding])).toThrow("binding-requires-live-evidence");
  });

  test("replays legacy evidence as immutable creates and rejects conflicts", () => {
    const item = evidenceItem("Owns API");
    const first = evidenceEvent("legacy-one", "archcontext.architecture-candidate-delta/v1", { evidenceItems: [item] });
    const identical = evidenceEvent("legacy-two", "archcontext.architecture-candidate-delta/v1", { evidenceItems: [item] });
    expect(replayArchitectureLedgerEvidenceState([first, identical]).evidenceItems).toEqual([item]);

    const conflicting = evidenceEvent("legacy-conflict", "archcontext.architecture-candidate-delta/v1", {
      evidenceItems: [{ ...item, summary: "Conflicting summary" }]
    });
    expect(() => replayArchitectureLedgerEvidenceState([first, conflicting])).toThrow("conflicting-legacy-create");
  });

  test("rejects mixed legacy and lifecycle evidence payloads", () => {
    const item = evidenceItem("Owns API");
    const mixed = evidenceEvent("mixed", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceItems: [item],
      evidenceOperations: [{ target: "item", action: "create", evidenceId: item.evidenceId, value: item }]
    });
    expect(() => validateArchitectureLedgerEvent(mixed)).toThrow("evidence lifecycle and legacy evidence cannot be mixed");
    const wrongVersion = evidenceEvent("wrong-version", "v1", {
      evidenceOperations: [{ target: "item", action: "create", evidenceId: item.evidenceId, value: item }]
    });
    expect(() => validateArchitectureLedgerEvent(wrongVersion)).toThrow("evidence lifecycle requires archcontext.architecture-evidence-lifecycle/v2");
    const lifecycleWithLegacyOnly = evidenceEvent("lifecycle-legacy", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceItems: [item]
    });
    expect(() => validateArchitectureLedgerEvent(lifecycleWithLegacyOnly)).toThrow("lifecycle V2 forbids legacy evidence arrays");
    const unknownAction = evidenceEvent("unknown-action", ARCHITECTURE_EVIDENCE_LIFECYCLE_PAYLOAD_VERSION, {
      evidenceOperations: [{ target: "item", action: "destroy", evidenceId: item.evidenceId, previousDigest: evidenceLifecycleValueDigest(item), reasonCode: "invalid" }]
    });
    expect(() => validateArchitectureLedgerEvent(unknownAction)).toThrow("unsupported action");
  });
});

function evidenceEvent(suffix: string, payloadVersion: string, payload: unknown): ArchitectureEventV1 {
  return {
    schemaVersion: "archcontext.architecture-event/v1",
    eventId: `arch_event.evidence_${suffix}`,
    eventType: "architecture.evidence.lifecycle",
    payloadVersion,
    repository: scope.repository,
    worktree: scope.worktree,
    baseDigest: digestJson({ base: suffix } as unknown as Json),
    resultingDigest: digestJson({ head: suffix } as unknown as Json),
    headSha: scope.worktree.headSha,
    actor: { kind: "daemon", id: "archctxd.test" },
    source: "apply_update",
    timestamp: "2026-07-11T00:00:00.000Z",
    idempotencyKey: `evidence-${suffix}`,
    provenance: { producer: "test", command: "test evidence lifecycle", inputDigest: digestJson(payload as Json) },
    payload: payload as Json
  };
}

function evidenceItem(summary: string): EvidenceItemV2 {
  return {
    schemaVersion: "archcontext.evidence-item/v2",
    evidenceId: "evidence.api",
    kind: "architecture-declaration",
    strength: "declared",
    polarity: "positive",
    origin: "runtime-daemon",
    subject: "module.api",
    selector: { kind: "path", id: "module.api", path: "packages/api" },
    summary,
    coverage: { level: "complete", scope: "module.api" },
    supports: ["checkpoint"],
    provenance: { producer: "test", command: "test evidence lifecycle", inputDigest: digestJson({ summary } as unknown as Json) },
    createdAt: "2026-07-11T00:00:00.000Z",
    digest: digestJson({ evidenceId: "evidence.api", summary } as unknown as Json)
  };
}

function evidenceBinding(evidenceId: string): EvidenceBindingV1 {
  return {
    schemaVersion: "archcontext.evidence-binding/v1",
    bindingId: "binding.api",
    evidenceId,
    target: { kind: "entity", id: "module.api" },
    bindingReason: "direct-selector",
    authorityEffect: "checkpoint-eligible",
    createdAt: "2026-07-11T00:00:00.000Z",
    provenance: { producer: "test", command: "test evidence lifecycle", inputDigest: digestJson({ evidenceId } as unknown as Json) }
  };
}

function modelFile(path: string, lines: string[] | string): ArchitectureLedgerModelFile {
  const body = Array.isArray(lines) ? lines.join("\n") : lines;
  return {
    path,
    body,
    digest: digestJson({ path, body } as unknown as Json)
  };
}
