import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { digestJson, stableId, type Json, type ModelExportResult, type RendererPort } from "@archcontext/contracts";

export interface NativeNode extends Record<string, Json | undefined> {
  id: string;
  kind: string;
  name: string;
  status?: string;
  summary?: string;
}

export interface NativeRelation extends Record<string, Json> {
  id: string;
  kind: string;
  source: string;
  target: string;
  intent: string;
}

export interface NativeModel {
  nodes: NativeNode[];
  relations: NativeRelation[];
}

export class NativeRenderer implements RendererPort {
  async renderProjection(input: { modelDigest: string; model: unknown[] }) {
    const model = normalizeNativeModel({ nodes: input.model as NativeNode[], relations: [] });
    return exportMermaidModel(model).files;
  }
}

export function normalizeNativeModel(model: NativeModel): NativeModel {
  return {
    nodes: [...model.nodes].sort((a, b) => a.id.localeCompare(b.id)),
    relations: [...model.relations].sort((a, b) => a.id.localeCompare(b.id))
  };
}

export function exportMermaidModel(model: NativeModel): ModelExportResult {
  const normalized = normalizeNativeModel(model);
  const lines = ["%% Generated by ArchContext. Native model remains source of truth.", "flowchart LR"];
  for (const node of normalized.nodes) {
    lines.push(`  ${mermaidId(node.id)}["${escapeMermaid(node.name)}"]`);
  }
  for (const relation of normalized.relations) {
    lines.push(`  ${mermaidId(relation.source)} -->|"${escapeMermaid(relation.kind)}"| ${mermaidId(relation.target)}`);
  }
  const content = `${lines.join("\n")}\n`;
  return {
    format: "mermaid",
    digest: digestJson({ format: "mermaid", content } as unknown as Json),
    files: [{ path: ".archcontext/generated/architecture.mmd", content }]
  };
}

export function loadNativeModelFromArchContext(root: string): NativeModel {
  return {
    nodes: readYamlObjects(resolve(root, ".archcontext/model/nodes")) as NativeNode[],
    relations: readYamlObjects(resolve(root, ".archcontext/model/relations")) as NativeRelation[]
  };
}

export function mermaidId(id: string): string {
  return stableId(id).replace(/-/g, "_").replace(/\./g, "_");
}

function readYamlObjects(dir: string): Record<string, Json>[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((file) => /\.ya?ml$/.test(file))
    .sort()
    .map((file) => parseFlatYaml(readFileSync(resolve(dir, file), "utf8")));
}

function parseFlatYaml(body: string): Record<string, Json> {
  const out: Record<string, Json> = {};
  for (const line of body.split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    const [, key, raw] = match;
    if (raw.startsWith("\"") && raw.endsWith("\"")) out[key] = JSON.parse(raw);
    else if (raw === "true" || raw === "false") out[key] = raw === "true";
    else out[key] = raw;
  }
  return out;
}

function escapeMermaid(value: string): string {
  return value.replace(/"/g, "'");
}
